### ISSUE TITLE
nested "hi" elements in text produce multiple entries in apparatus

### ISSUE THREAD

**Issue by andreabernini** [DCLP/dclpxsltbox#126]
In P.Oxy. 75.5028 (TM 128956; https://github.com/DCLP/idp.data/blob/dclp/DCLP/129/128956.xml#l87) the Leiden+:

 ὕ( ῾´)ληι.

is displayed as:

ὑληι. papyrus : ὑύὑληι. papyrus

we would expect:

ὕληι. papyrus

**Comment by paregorios** [comment]
This bug is presumably because the XSLT doesn't handle the presence of the ```hi``` elements indicating accent and breathing:

```xml
<hi rend="asper"><hi rend="acute">ὕ</hi></hi>ληι
```

At first glance, I was troubled by the apparent redundancy in this encoding: using the unicode upsilon with lenis and asper and also marking up with ```<hi>```, but I assume (can you correct me @andreabernini ?) that this is because the diacriticals actually appear on the papyrus (whence the use of ```<hi>```). In any case, this reminds me of another case where it may be the same bit of XSLT involved, namely #130 .

**Comment by paregorios** [comment]
@cgajjar05 please investigate the navigator XSLT (and possibly the underlying epidoc XSLT) to see if you can find where (and whether) ```<hi rend="asper">``` and ```<hi rend="acute">``` are being handled? Prelim to figuring out what we're getting the odd output [reported by @andreabernini above](https://github.com/DCLP/dclpxsltbox/issues/126#issue-64497202) (see also [HTML of P. Oxy. 75 5028](http://dclp.github.io/dclpxsltbox/output/dclp/129/128956.html) line 4 at the end and [associated apparatus entry](http://dclp.github.io/dclpxsltbox/output/dclp/129/128956.html#to-app-hi05), which is what @andreabernini repeats). I bet the problem has something to do with nested ```<hi>``` elements, but see what you find.

**Comment by paregorios** [comment]
Blocker for #124 and #130.

**Comment by andreabernini** [comment]
P.Oxy. 5032 (TM 128960) contains various samples:

col. II 139 https://github.com/DCLP/idp.data/blob/dclp/DCLP/129/128960.xml#l151
Leiden+: Ἀχι]λ ῆ(^)’
Displayed in the apparatus: ῆ’ papyrus
Expected: ῆ papyrus

col. II 139 https://github.com/DCLP/idp.data/blob/dclp/DCLP/129/128960.xml#l151
Leiden+:  ἴ(¨´)σ̣χ̣ωσι
Displayed in the apparatus: ϊσ̣χ̣ωσι papyrus : ϊίϊσ̣χ̣ωσι papyrus 
Expected: ΐσ̣χ̣ωσι papyrus

col. II 152 https://github.com/DCLP/idp.data/blob/dclp/DCLP/129/128960.xml#l164
Leiden+:  ἰ(´¨) ή(´) ϊ(¨)ε
Displayed in the apparatus: 
^ ii.34. ίήϊε papyrus : ίϊίήϊε papyrus
^ ii.34. ίήϊε papyrus
^ ii.34. ίήϊε papyrus
Expected: ΐήϊε papyrus

col. II 150 https://github.com/DCLP/idp.data/blob/dclp/DCLP/129/128960.xml#l162
the system does not accept the combinations I wrote

**Comment by paregorios** [comment]
@leoba please review the above old discussion and look at output to see if the behavior indicated is still happening. If so, please see if you can address the deficiencies described above. If the situation is fixed or changed, please update here with explanatory comment and links to examples. Thanks.

**Comment by leoba** [comment]
After looking over the examples, I think this is three different issues:

[https://github.com/DCLP/idp.data/blob/master/DCLP/129/128960.xml#L162](https://github.com/DCLP/idp.data/blob/master/DCLP/129/128960.xml#L162) (Displayed in the apparatus: ϊσ̣χ̣ωσι papyrus : ϊίϊσ̣χ̣ωσι papyrus): Is tagged `<hi rend="diaeresis"><hi rend="acute">ἴ</hi></hi><unclear>σχ</unclear>ωσι` so there is a nested `<hi>` happening, with a different view for each being generated in the apparatus which need to be combined into one. This seems to be the main ask on this issue, and it’s the one I’ll focus on in Issue 126.

The other two examples, which are different and which should have their own issues, are:


[https://github.com/DCLP/idp.data/blob/master/DCLP/129/128960.xml#L162](https://github.com/DCLP/idp.data/blob/master/DCLP/129/128960.xml#L162) (Displayed in the apparatus: ῆ’ papyrus): Is tagged `<hi rend="circumflex">ῆ</hi>’`, there is no nesting happening here. It appears that the ‘ is being generated in the apparatus when it shouldn’t be (or else the ‘ that is typed there is coming along for the ride)

[https://github.com/DCLP/idp.data/blob/master/DCLP/129/128960.xml#L175](https://github.com/DCLP/idp.data/blob/master/DCLP/129/128960.xml#L175) (Displayed in the apparatus: ίήϊε papyrus : ίϊίήϊε papyrus, plus two additional entries): The complete tagging here is `<hi rend="acute"><hi rend="diaeresis">ἰ</hi></hi><hi rend="acute">ή</hi><hi rend="diaeresis">ϊ</hi>ε` -so we have a nested hi, which results in the duplicate views on the same line (what we see in the first example), but there’s the additional problem that each time there is a `<hi>` tag a new entry is generated for the apparatus, resulting in multiple entries for the same word. This seems like a more difficult problem to solve, since the words themselves aren’t tagged, but it should be its own issue.

I am going to work here on the nested <hi> issue, and the others should be separated into new issues.

**Comment by paregorios** [comment]
@leoba thanks, that sounds like a good plan; shall I undertake to create the two new issues you enumerate above?

**Comment by paregorios** [comment]
Per @leoba's suggestion above, this ticket is now solely about:

> [https://github.com/DCLP/idp.data/blob/master/DCLP/129/128960.xml#L162](https://github.com/DCLP/idp.data/blob/master/DCLP/129/128960.xml#L162) (Displayed in the apparatus: ϊσ̣χ̣ωσι papyrus : ϊίϊσ̣χ̣ωσι papyrus): Is tagged `<hi rend="diaeresis"><hi rend="acute">ἴ</hi></hi><unclear>σχ</unclear>ωσι` so there is a nested `<hi>` happening, with a different view for each being generated in the apparatus which need to be combined into one. This seems to be the main ask on this issue, and it’s the one I’ll focus on in Issue 126.

It has been retitled to reflect the narrowing of scope. The other two concerns originally included by @andreabernini have been split out as #240 and #241.

**Comment by leoba** [comment]
I'm very sorry this has taken so long; most of that time has been figuring out were exactly I needed to change code. I think I have fixed this. I have made changes to two files in navigator/epidoc-xslt.

1. htm-tpl-apparatus.xsl: Added a bit of code to the xsl:for-each instructing that the stylesheet not take any `hi` that have ancestors that are also `hi`. The immediate effect is that the second footnote (the one created by the child `hi` tag) is not displayed. This should satisfy [Issue 241](https://github.com/DCLP/dclpxsltbox/issues/241).

2. tpl-apparatus.xsl: Within template hirend_print is where the diacritics are added. I searched the DCLP data and found just a few instances of nested `hi`, one had diaeresis within acute and the other acute within diaeresis. So for an immediate fix I added a `choose` statement in the existing `when` statements for both diaeresis and acute, which look for `child::t:hi` with `@rend='diaeresis'` (for the acute) and `@rend='acute'` (for the diaeresis) and combine the diacritics. 

Result: `ΐσ̣χ̣ωσι papyrus` - which looks to be what @andreabernini is expecting.

**Comment by paregorios** [comment]
I see these changes were committed to the dclp branch on the epidoc stylesheets subversion repos with [r2588](https://sourceforge.net/p/epidoc/code/2588/) and [r2599](https://sourceforge.net/p/epidoc/code/2589/), so their effects are already reflected in latest demo transforms ... e.g. (for examples listed above):

 - [P.Oxy. 75.5028 (TM 128956)](http://dclp.github.io/dclpxsltbox/output/dclp/129/128956.html), line 4 at end (```ὕ(*)(*)ληι```) and associated apparatus entry (```ὑληι. papyrus```)
 - P.Oxy. 5032 (TM 128960)
  - column ii, line 21 (```[ἢ Ἀχι]λῆ(*)```) and associated apparatus entry (```ῆ papyrus```)
  - column ii, line 21 (```ἴ(*)(*)σ̣χ̣ωσι```) and associated apparatus entry (```ΐσ̣χ̣ωσι papyrus```)

Closing as resolved.
