### ISSUE TITLE
date repetition in some bibliographic citations

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#171]
found by @leoba and split out from #146:

the date displays twice (once in parenthesis, once out) and although there are page numbers indicated they are not displaying (there is an empty "pp. ." instead):

https://github.com/DCLP/idp.data/blob/master/Biblio/79/78209.xml#L12-L23 (HTML: https://github.com/DCLP/dclpxsltbox/blob/master/output/dclp/101/100062.html#L46)

**Comment by leoba** [comment]
This issue has two parts:
1. date displaying twice: Not a bug. In this case (and others) the issue number of the article is the date of publication. What's displaying is "issue (date)". Nothing to change! I'll add that it looks especially odd in this case because the name of the journal isn't getting pulled in from the Biblio citation, because it's not there. In cases where the journal name displays it is obvious that the first date is in fact the issue identifier.

2. Page numbers not displaying (empty "pp. " instead). When I made this note on issue 146 there were no page numbers displaying in the cited HTML, but they are displaying now. I assume that whatever the problem was has been fixed in the meantime.

I thereby declare this issue close-able.

**Comment by jcowey** [comment]
Related to #170

**Comment by jcowey** [comment]
The problem of double date display should be fixed, so possibly this issue should remain open, what do you think @paregorios ?

**Comment by paregorios** [comment]
@jcowey I'm confused. Do you think this issue should be closed, or is there still something to do?

**Comment by jcowey** [comment]
As you can see from the comment above, the commit has now been made to master biblio, e.g.
https://github.com/papyri/idp.data/blob/master/Biblio/80/79621.xml#L7

As long as everything in DCLP is operating from 
https://github.com/papyri/idp.data/tree/master/Biblio
(as I think it is)
then everything should now be fine.
That would mean this issue can be closed. Hope this goes some way to clarifying the situation.

**Comment by leoba** [comment]
A clarifying question for @paregorios - is DCLP operating from papyri (as indicated by @jcowey above)? So I shouldn't be concerned that important changes in papyri aren't reflected in DCLP? Compare the examples from #170 :

https://github.com/papyri/idp.data/blob/master/Biblio/81/80929.xml#L7
with
https://github.com/DCLP/idp.data/blob/master/Biblio/81/80929.xml#L7

If yes then both #170 and this one can be closed. If not they need to be merged.

**Comment by jcowey** [comment]
https://github.com/DCLP/idp.data/blob/master/Biblio/81/80929.xml#L7
look at 
https://github.com/DCLP/idp.data/blob/dclp/Biblio/81/80929.xml#L7
instead

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/blob/master/Biblio/81/80929.xml#L7
and
https://github.com/DCLP/idp.data/blob/dclp/Biblio/81/80929.xml#L7
are in sync

**Comment by paregorios** [comment]
Agree this is completely resolved, so closing. 

Reiterating here that the deployable, production branch of idp.data for litpap.info is "dclp", not "master".

Noting and agreeing also with @leoba's [comment above](https://github.com/DCLP/dclpxsltbox/issues/171#issuecomment-196046675) that apparent repetitions like "2008 (2008)" are the consequence of identical values occurring in both ```<issue>``` and ```<date>```. This will be infrequent and should not confuse anyone. Therefore, we're not going to mess with it.
