### ISSUE TITLE
Include @corresp in Leiden+

### ISSUE THREAD

**Issue by HolgerEssler** [DCLP/dclpxsltbox#177]
In most of the Herculaneum and other files text-divs have a corresp-Attribute, e.g.
https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59436.xml#L646
This currently prevents transformation to Leiden+.
Thus we want to transform and display the corresp-attribute also in Leiden+:
Suggested solution:
In the example 
`<div n="1" subtype="column" type="textpart" corresp="#FR365"><ab>`
should transform to
`<D=.1.column.#FR365<=`

**Comment by jcowey** [comment]
See also #184

**Comment by HolgerEssler** [comment]
Related to #175

**Comment by paregorios** [comment]
Bumping this to high priority, because it is a blocker for testing any and all Leiden+ issues in the editor for files that have corresps.

**Comment by paregorios** [comment]
blocker for #149

**Comment by paregorios** [comment]
[This](https://github.com/DCLP/xsugar/compare/master...DCLP:issue177) is ready for review in an editor instance. 

@Edelweiss what do you think is the best way to let @HolgerEssler test this functionality in the editor? Is there a development version of the editor for which the xsugar branch could be switched from "master" to "issue177"? 

What I've done:

 - Modified the grammar to support this option
 - Added a unit test in the xsugar repos that verifies the grammar is working as expected (round trip)
 - Added a mocked up XML file against which xsugar coverage tests run successfully.

What I can't do successfully is run TM 59436 through XSugar standalone because it has other, unrelated parse errors related to the ```<unclear>``` tag and the values in the ```n``` attribute on ```<lb>```.

**Comment by HolgerEssler** [comment]
@paregorios The problems you are pointing to at the end of your last comment seem to originate from bad encoding. I have undertaken to have it corrected and will let you know, once it is uploaded. This is not to prevent @Edelweiss from pointing me to a development version, but correcting the xml might be the quicker way - and it needs to be done in any case.

**Comment by HolgerEssler** [comment]
@paregorios updated XML under https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59436.xml
Does this allow us to move on?

**Comment by paregorios** [comment]
@HolgerEssler I will run a coverage test using XSugar Standalone today on the updated file, which should give us more confidence in the result (or point to additional work).

Meantime, I am still waiting to hear from @Edelweiss as to how we can get you a way to test this fix in an instance of the editor.

cc @jcowey @rla2118

**Comment by paregorios** [comment]
@HolgerEssler 59436 was committed to the deprecated "dclp" branch of idp.data. I have "cherry-picked" that commit (which also included a new file "DCLP/63/Untitled1.xml") into the "master" branch. This allowed me to run the test. The old fragment parse errors are indeed gone, so I think this issue is resolved. In the absence of any response to my queries about a mechanism for a way to let you test this in an editor instance, I am going to go ahead and deploy this change so we can continue working on other matters.

**Comment by paregorios** [comment]
Note that this capability will not be available in the editor at litpap.info until @Edelweiss or @m-k-r pulls the latest changes from DCLP/xsugar "master" branch.
