### ISSUE TITLE
DDbDP texts in DCLP

### ISSUE THREAD

**Issue by rla2118** [DCLP/dclpxsltbox#188]
There are some texts in DCLP that have come via the DDbDP.  Here are two examples:

http://litpap.info/dclp/58918

http://litpap.info/dclp/16422

Opening them, you'll notice that there is no DCLP/LDAB metadata, only that of HGV.  

My preference would be to see both the HGV and DCLP/LDAB data.

**Comment by paregorios** [comment]
@hcayless We're wondering if you can give us some guidance as to where to intervene in the navigator code base to get a combined HTML display when a given papyrological text appears in both DDBDP/HGV and DCLP. @rla2118 has [spotted a couple](https://github.com/DCLP/dclpxsltbox/issues/188#issue-188256426) where we're not getting what we expect.. Do you suppose this is about mapping, or should be looking elsewhere?

**Comment by Edelweiss** [comment]
In order to display DCLP meta data alongside HGV, Apis and DDbDP, the relations between DDbDP and DCLP need to be passed on to the script that creates the static HTML files:

https://github.com/papyri/navigator/blob/master/pn-xslt/MakeHTML.xsl#L75

https://github.com/papyri/navigator/blob/master/pn-xslt/MakeHTML.xsl#L85

MakeHTML.xsl currently handles only the following relations:
* apis
* hgv
* trismegistos.org
* ddbdp
* hgvtrans

Code to deal with DCLP relations needs to be embed into the code responsible for creating DDbDP files:

https://github.com/dclp/navigator/blob/xslt-master/pn-xslt/MakeHTML.xsl#L291

**Comment by paregorios** [comment]
@Edelweiss as this is principally an XSLT task, should the NYU team pick it up?

**Comment by Edelweiss** [comment]
Thank you, Tom. Yes, this is principally an XSLT task. It mainly concerns the html files that are created by the indexing process, but as it may also be something to do with the relations that are stored in the number server and/or with the parametrisation of the script (I’m not quite sure here). I think it’d be best if we try solve this issue here at Heidelberg, so that Marcel can put all the changes immediately to the test to see if they are producing the desired results.

**Comment by paregorios** [comment]
@Edelweiss ok.

**Comment by Edelweiss** [comment]
The xslt part of aggregating the data seems to be working. All that needed to be done was make sure that dclp paths are built correctly and that ddbdp knows how to deal with incoming dclp relations.

The parameter _related_ must be set to something like _http://papyri.info/dclp/58918 http://papyri.info/hgv/58918_. Only then will the script scoop secondary information from the corresponding HGV and DCLP files.

Example parametrisation, such as…

**collection** 	ddbdp
**related** 	http://papyri.info/dclp/58918 http://papyri.info/hgv/58918/source

…will result in…

**relations** 	http://papyri.info/dclp/58918, http://papyri.info/hgv/58918/source
* /srv/data/papyri.info/idp.data/HGV_meta_EpiDoc/HGV59/58918.xml
* /srv/data/papyri.info/idp.data/DCLP/59/58918.xml

**dclp** 	true
**ddbdp** 	true
**hgv** 	true
**tm** 	false
**image** 	false
**translation** 	false

https://github.com/DCLP/navigator/commits/issue188

Marcel will now make sure that the script is provided with the correct set of parameters. If this needs any change of the number server code, please reassign it to me.

**Comment by jcowey** [comment]
http://litpap.info/dclp/16422

now looks good

**Comment by jcowey** [comment]
So I am now closing this for now
