### ISSUE TITLE
Restore "Open in Editor" button

### ISSUE THREAD

**Issue by rla2118** [DCLP/dclpxsltbox#247]
The "open in editor" button, through which one could access the editor, has disappeared. Can it please be restored?

**Comment by paregorios** [comment]
This is an XSLT issue. 

To find the code area, search for "editthis" in MakeHTML.xsl.

**Comment by paregorios** [comment]
As I look at [the code history](https://github.com/DCLP/navigator/blame/master/pn-xslt/MakeHTML.xsl#L270), this seems never to have been available for DCLP (although a todo comment was added 3 years ago). 

@rla2118 : what's the priority on this?

**Comment by rla2118** [comment]
I would say that this is high priority.  Without it, it's not obvious to users how to access the editor.

**Comment by wsalesky** [comment]
@paregorios I'm happy to add. What is the link to the editor?

**Comment by jcowey** [comment]
If you go to
papyri.info/ddbdp/p.aberd;;16
(which is of course papyri.info)
you will see just below the title the following:
![bildschirmfoto 2017-03-24 um 16 20 42](https://cloud.githubusercontent.com/assets/612992/24300794/e4ac25f2-10ad-11e7-8e11-7ed08a06eb50.png)
That is the open in editor button. I think that there are mapping dependencies involved. Pretty sure that at one stage Marcel did have this working on our development site.

**Comment by wsalesky** [comment]
@jcowey Great, I will take a look. Thanks.

**Comment by jcowey** [comment]
@wsalesky if you are taking a look at pn-mapping and clojure and all that stuff please let us know. I say this because the whole business of indexing and mapping has been a constant cause of concern for building HTML pages in DCLP. It would be most helpful to have another person to ask for assistance

**Comment by paregorios** [comment]
jcowey: I think that's a separate concern to this, which is just about enabling link generation on the basis of existing information, but we should address the concern you raise here.

**Comment by paregorios** [comment]
based on [code analysis here](https://github.com/DCLP/navigator/blame/master/pn-xslt/MakeHTML.xsl#L270), we need to know which```idno[@type]``` should be thrown at ```/editor/publications/create_from_identifier/papyri.info/dclp/``` in order to open the editor properly. 

@jcowey @Edelweiss @m-k-r can any of you advise?

**Comment by jcowey** [comment]
I would have thought:
https://github.com/DCLP/idp.data/blob/master/DCLP/59/58911.xml#L11
rather than
https://github.com/DCLP/idp.data/blob/master/DCLP/59/58911.xml#L14
i.e. ``<idno type="dclp">\d+</idno>
but you had better get confirmation from @Edelweiss and @m-k-r 
before ploughing ahead

**Comment by m-k-r** [comment]
It was already [solved](https://github.com/DCLP/navigator/blob/issue188/pn-xslt/MakeHTML.xsl#L319), but never pushed to master. All our changes should be in navigator/sosol master now.

I am reindexing this weekend and "open in editor" should be back next week.

**Comment by paregorios** [comment]
Open in editor appears to be back at this time. @rla2118 can you confirm that it is working as you expect?

**Comment by jcowey** [comment]
I went to 
http://litpap.info/dclp_authors.html
Under Achilles Tatius the first number is
http://litpap.info/dclp/58911
It does NOT offer "Open in editor". The button is not there.
If you scroll down to 
Acta Alexandrinorum
and choose 
http://litpap.info/dclp/78911
(sb;22;15203)
then "open in editor" is available and works.
I am pretty sure that this is connected with a long standing problem. DCLP offers up DDbDP, HGV, APIS and DCLP.
Whenever DDbDP texts are available then the HGV data and the DDbDP data is offered and given preferential treatment. That appears to be the case in 
http://litpap.info/dclp/78911
Moreover I think that we now also have a regression on serving up HGV *and* DCLP metadata, whenever it is available:
https://github.com/DCLP/idp.data/blob/master/HGV_meta_EpiDoc/HGV79/78912.xml
and
https://github.com/DCLP/idp.data/blob/master/DCLP/79/78911.xml

**Comment by paregorios** [comment]
So that sounds like mapping issues. Perhaps @m-k-r can give as an update on where things stand in that regard ...

**Comment by m-k-r** [comment]
The files hadn't been copied from the development server yet. With the last indexing, "open in editor" is [back](http://dclp-test.zaw.uni-heidelberg.de/dclp/58911) but the problem @jcowey described still [exists](http://dclp-test.zaw.uni-heidelberg.de//dclp/78911).
For comparison I recreated the html files with the branch [issue188](https://github.com/DCLP/navigator/tree/issue188) again where this problem is [solved](http://litpap.info/dclp/78911). As far as I know the files changed in this branch are [MakeHTML.xsl](https://github.com/DCLP/navigator/blob/issue188/pn-xslt/MakeHTML.xsl) and [pi-functions.xsl](https://github.com/DCLP/navigator/blob/issue188/pn-xslt/pi-functions.xsl). These should be in my commits from last friday. I will look into it.

**Comment by m-k-r** [comment]
The problem is [solved](http://dclp-test.zaw.uni-heidelberg.de/dclp/78911).

**Comment by rla2118** [comment]
@m-k-r @paregorios Can we close this?

**Comment by paregorios** [comment]
Fine by me.
