### ISSUE TITLE
XML schema problem: @unit is invalid

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#262]
In accordance with the TEI Guidelines, we are using ```@unit``` on ```<biblScope>```, but this usage fails validation against the version of the EpiDoc guidelines we have hard-coded into our files: [8.13](http://www.stoa.org/epidoc/schema/8.13/tei-epidoc.rng). This is 10 minor versions down (current is 8.23). Recommend we assess whether we can step up to 8.23.

Assigning myself to run validation tests across the corpus in order to assess viability.

**Comment by jcowey** [comment]
@paregorios I would prefer to step up to 8.23. I have this in mind for papyri.info too. Some months back I had Carmen make a commit for the `@unit` change and also one for the `graphic url` old stuff we still have in papyri.info. I simply failed to get everything organised with Ryan and Hugh in order to prepare for testing and then making a release of new code. 
We do those things "properly" now in DCLP and I would see it as a step backwards to quite an extent, if we were to walk back. Just a thought from me.

**Comment by paregorios** [comment]
It turns out that someone's already done what needed doing here, namely changing the oxygen schema directive to point at the "latest" version of the EpiDoc schema, rather than pinning to the down version. Closing because there's nothing left to do.
