### ISSUE TITLE
Add "Create New DCLP Publication" button

### ISSUE THREAD

**Issue by ryanfb** [DCLP/dclpxsltbox#330]
This issue is for tracking a desideratum that has come out of our Skype discussions, that in addition to the "Create New Publication" button on the "Advanced Create" page in the editor (which will create a Publication with a stubbed HGVMetaIdentifier and DDbDPIdentifier), there should be a "Create New DCLP Publication" button (which will create a Publication with a stubbed DCLPMetaIdentifier and DCLPTextIdentifier).

Perhaps the "Create New Publication" button should also be reworded to e.g. "Create New HGV/DDbDP Publication"?

Depends on #329. Related to #304.

**Comment by m-k-r** [comment]
https://github.com/DCLP/sosol/commit/3a9a663910a86d30fea762bc9f12896d5f68f87e

**Comment by Edelweiss** [comment]
After the creation of a new DCLP file, the dashboard keeps throwing errors because the title of the publication and the name of the identifier are empty:

https://github.com/DCLP/sosol/blob/issue330/app/models/publication.rb#L386
https://github.com/DCLP/sosol/blob/issue330/app/models/dclp_meta_identifier.rb#L62

Once this hurdle has been cleared, there is still the need to create a DCLPTextIdentifier alongside the DCLPMetaIdentifier:

https://github.com/DCLP/sosol/blob/issue330/app/models/publication.rb#L396

See [commit](https://github.com/DCLP/sosol/commit/f94cc41c9f59d3da70540cefb9718acbaafcae23) in SoSOL branch [issue330](https://github.com/DCLP/sosol/tree/issue330) on github
