### ISSUE TITLE
Implement handling for ancient "apostrophe" mark in XSLT

### ISSUE THREAD

**Issue by cgajjar05** [DCLP/dclpxsltbox#63]
Create or change representation in preview (XSLT) for "Apostrophe".

**Comment by paregorios** [comment]
XML markup:
```xml
<g type="apostrophe"/>
```

@rla2118 @jcowey @HolgerEssler please indicate what you would like to see in the HTML output for this ...

**Comment by rla2118** [comment]
g types don't appear in the apparatus, right?  Anyway to make them into high rends and display like other diacriticals in the app.crit.? @jcowey

**Comment by paregorios** [comment]
@rla2118 I'd be inclined to keep them as ```<g type="apostrophe"/>``` since they are separate characters, rather than additive like accents and breathings. That would save us churning the data and instead just add handling in the XSLT for this particular type of ```<g>```.

**Comment by rla2118** [comment]
OK.  As for display, I would opt for the modern apostrophe.

**Comment by paregorios** [comment]
@rla2118 what do you want the corresponding apparatus entry to look like? 

The way that TM64437 is marked up:

```xml
<lb n="27"/><gap reason="lost" extent="unknown" unit="character"/> <supplied reason="lost">π</supplied>αρ’ <g type="apostrophe"/> αὐ<unclear>τ</unclear>ό ἐστιν πάθος <g type="diple-obelismene"/> <gap reason="lost" extent="unknown" unit="character"/>
```

there is whitespace before and after the ```<g type="apostrophe"/>```, but there is also a hard-coded apostrophe unicode character post-fixed to the rho immediately preceding. Is this redundant, or something else?

**Comment by wsalesky** [comment]
@paregorios @rla2118 
I can update the XSLT, can you clarify what the HTML output should be? 
Thanks.

**Comment by paregorios** [comment]
@rla2118 @HolgerEssler @jcowey @rogerbagnall please respond to questions above about what you want to see in the HTML for this. Thanks.

**Comment by rla2118** [comment]
If we don't want to make this a hi-rend, then I suggest displaying the g-type as an apostrophe and suppressing or removing the typed apostrophe so that we don't get the redundant display.  IOW, it should display as π]αρ’ instead of  π]αρ’ ’ and the g-type should be recorded in the XML. Is that OK?

**Comment by rogerbagnall** [comment]
To the limits of my understanding of the question, I think Rodney's proposal is fine.

**Comment by HolgerEssler** [comment]
Another solution would be to handle this g-type in analogy with what we are doing in the case of ancient punctuation (#67), where we have e.g. period next to ((low-punctus)). Thus here we could have π]αρ’ ((apostrophe)) to show that the accent is present in the original.

**Comment by rla2118** [comment]
This would mean, I presume, that double consonants divided by an apostrophe would look something like, e.g., Λόγ((apostrophe))γου, which I don't like. I'd in fact prefer redundant apostrophes to that.

**Comment by wsalesky** [comment]
@paregorios 
A few clarifying questions:

- The original question is for 

> Create or change representation in preview (XSLT) for "Apostrophe".

- Is this in the editor, or is this the XSLT that handles the following output: http://dclp.github.io/dclpxsltbox/output/dclp/65/64473.html

- Also is the intention to change the display in the apparatus (adding it to the apparatus), or in the text display? 

- Is the consensus to have the example output as: π]αρ’ instead of π]αρ’ ’

**Comment by paregorios** [comment]
@wsalesky this is for the XSLT.

@rla2118 @rogerbagnall @HolgerEssler @jcowey unfortunately, the discussion above has ranged around the issue but not yet provided enough clarity for implementation. Please confirm or correct the following assertions (i.e., my best guesses regarding questions introduced above) regarding handling of ```<g type="apostrophe">``` in HTML transforms:

1. In the text itself, render ```<g type="apostrophe"/>``` as the modern, unicode apostrophe character, e.g., for ```παρ<g type="apostrophe"/>``` render ```παρ'```.

2. Create a corresponding apparatus entry that reads e.g., ```παρ' papyrus```.

3. In order to eliminate cases like TM64437 where we are currently getting e.g. ```παρ''``` in HTML, we will have to modify XML to eliminate the current, redundant encoding like ```παρ' <g type="apostrophe"/>```.

**Comment by paregorios** [comment]
cc @jds15

**Comment by rla2118** [comment]
I'm fine with those assertions.

**Comment by rogerbagnall** [comment]
I am also.

**Comment by paregorios** [comment]
Thanks all.

@wsalesky, please see [above](https://github.com/DCLP/dclpxsltbox/issues/63#issuecomment-309415371)

**Comment by jds15** [comment]
Just seeing this now, but just to be clear:

these are all cases in which you mean to indicate that there is an ancient apostrophe on the papyrus, right? i only ask because there was a conflation lenis; so, want to make sure that this isn’t similar.

josh

--
Associate Professor in Class
ical Studies & History, Duke
University | Duke Collaborat
ory for Classics Computing |
Greek, Roman and Byzantine S
tudies | Duke Data Bank of D
ocumentary Papyri | papyri.i
nfo | people.duke.edu/~jds15<http://people.duke.edu/~jds15>


On Jun 19, 2017, at 8:23 AM, Tom Elliott <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks all.

@wsalesky<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_wsalesky&d=DwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=EvYAdK47yjleTNIG5WovbBvM8KyL8BPnUvRstzlgENY&s=sIttJQRkfF-yy_yf25yXpYsZw16isYwJyjFyzM2Uo6k&e=>, please see above<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DCLP_dclpxsltbox_issues_63-23issuecomment-2D309415371&d=DwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=EvYAdK47yjleTNIG5WovbBvM8KyL8BPnUvRstzlgENY&s=fcKNmDBsgg1ztohuywvv2fiCObMyHtFqdNqi8e5t5xI&e=>

**Comment by jds15** [comment]
If this indeed marks an ancient apostrophe, then I'd change Tom's formulation slightly, to:

1. In the text itself, enter παρ’<g type="apostrophe"/> and render παρ' (XSLT has to ignore <g type>

2. In the apparatus print παρ' papyrus.

3. XSLT has to ignore unicode '

Why? Because if I understand Tom's method assumes that where a scribe has written an apostrophe a modern editor will do the same; but this will not always be true. So, we must enter both bits and suppress one or the other depending on context (text or app)

**Comment by rla2118** [comment]
@paregorios I agree with jds15's amendment. How do you want to proceed with this?

**Comment by wsalesky** [comment]
@rla2118 @paregorios 
I can take care of this.

**Comment by wsalesky** [comment]
@paregorios @rla2118 `t:g` does not trigger an apparatus entry, should it? If not, the code in this branch, should accomplish output in text and apparatus (when triggered by other apparatus elements) the suggestions by @jds15. 
 
Branch: `https://github.com/DCLP/epidoc-xslt/tree/issue63`

**XSLT changed** 
`epidoc-xslt/htm-teig.xsl`
Added:
`<xsl:param name="location" tunnel="yes" required="no"></xsl:param>`

And to suppress output of duplicate apostrophe in text. 
```
<xsl:if test="$location='apparatus'">
               <xsl:text>’</xsl:text>
               <xsl:call-template name="g-unclear-symbol"/>               
</xsl:if>
```
**XSLT changed** 
`epidoc-xslt/tpl-apparatus.xsl`
Added a replace to the 'trans-string' template to remove unicode apostrophe in apparatus. 
`<xsl:value-of select="replace(translate($trans-text, $all-grc, $grc-lower-strip),'''','')"/>`

HTML:
```
diff --git a/output/dclp/113/112359.html b/output/dclp/113/112359.html
index 4be16d74c0..1c80aeb199 100644
--- a/output/dclp/113/112359.html
+++ b/output/dclp/113/112359.html
- id="ar-l54">Βηθ'’σαϊ
+ id="ar-l54">Βηθ'σαϊ
- <span>βηθ'’σαϊδ̣[α-
+ <span>βηθ’σαϊδ̣[α-

diff --git a/output/dclp/113/112371.html b/output/dclp/113/112371.html
index 5760e63b71..45c98b7f19 100644
--- a/output/dclp/113/112371.html
+++ b/output/dclp/113/112371.html
- id="ar-ii-l4">ἐγ’γύς<br
+ id="ar-ii-l4">ἐγγύς<br
```
I think the XML needs to be updated with @jds15 suggested encoding. This does not seem to be standard yet.

**Comment by paregorios** [comment]
@jds15 or @jcowey please clarify whether or not there should be whitespace in the XML between the Unicode apostrophe character and the ```<g type="apostrophe"/>``` element? So, for example, which of the following should we see in the XML:

```xml
<supplied reason="lost">π</supplied>αρ’ <g type="apostrophe"/> αὐ<unclear>τ</unclear>ό
```

(which is what I'm currently seeing in many files)

or 

```xml
<supplied reason="lost">π</supplied>αρ’<g type="apostrophe"/> αὐ<unclear>τ</unclear>ό
```

(which is what I would assume to be correct).

Once we get that question answered clearly and definitively then we can actually move forward on implementation.

**Comment by paregorios** [comment]
ping @jds15 @jcowey cc @hcayless 

If I don't hear back from one of you, I'm going to make a command decision about this on my own.

**Comment by jcowey** [comment]
Repeating comment from @jds from 19 June

If this indeed marks an ancient apostrophe, then I'd change Tom's formulation slightly, to:
 * In the text itself, enter παρ’<g type="apostrophe"/>and render παρ' (XSLT has to ignore <g type>
 * In the apparatus print παρ' papyrus.
 *  XSLT has to ignore unicode '

Why? Because if I understand Tom's method assumes that where a scribe has written an apostrophe a modern editor will do the same; but this will not always be true. So, we must enter both bits and suppress one or the other depending on context (text or app)

To answer question from @paregorios immediately above:
there should be NO whitespace at entry
`<supplied reason="lost">π</supplied>αρ’<g type="apostrophe"/> αὐ<unclear>τ</unclear>ό`

Essential to have the modern apostrophe entered (pragmatically through copy and paste that is going to happen anyway, and for thinking editors, they are far more likely to insist on modern diacritics, while wanting to record ancient ones). 
In the text display ignore the `<g type="apostrophe"/>` and display
`<supplied reason="lost">π</supplied>αρ’ αὐ<unclear>τ</unclear>ό` 

In the app. print
**παρ' papyrus**

**Comment by jcowey** [comment]
I suppose insisting on NO whitespace as above could also be circumvented by making the display XSLT "clever"
In the case of 
`<supplied reason="lost">π</supplied>αρ’ <g type="apostrophe"/> αὐ<unclear>τ</unclear>ό`
ignore `<g type="apostrophe"/>` and make sure that there is one whitespace between 
`<supplied reason="lost">π</supplied>αρ’` and `αὐ<unclear>τ</unclear>ό`
for the text display

App display would operate by going back to last Greek letter before the `<g type="apostrophe"/>`  and then adding the apostrophe immediately after that said Greek letter, in this case the rho.

**Comment by paregorios** [comment]
so @jcowey you'd never want to be able to encode a case where there *is* whitespace before the apostrophe? Or in that case would you insist on marking a vacat with ```<space>```?

**Comment by jcowey** [comment]
Always wary of the word "never"! Whitespace before the apostrophe seems very unlikely, but your caution is probably good. Does that help?

**Comment by paregorios** [comment]
Actually, I think the only reason (now having discussed it with @hermaion82) to abhor the space between the modern apostrophe and the ```<g>``` is that it might confuse a human reading the text. But there's no reason we shouldn't have the XSLT ignore the whitespace as @jcowey suggests.

**Comment by paregorios** [comment]
I'm taking this for testing.

**Comment by paregorios** [comment]
@wsalesky I'm using TM64473 for testing (first fragment A, line 27)

XML:
```xml
<supplied reason="lost">π</supplied>αρ’ <g type="apostrophe"/> αὐ<unclear>τ</unclear>ό ...
```

HTML generated by the code from issue63 branch is as I expect:
```
[ -ca.?- π]αρ’ αὐτ̣ό ...
```

But we should also see an apparatus entry like:

```
π]αρ’ papyrus
```

or some such (I'm not sure what current apparatus code will do with the preceding ```<supplied>```). 

So, to answer the question you asked above ("t:g does not trigger an apparatus entry, should it?"):

Yes, t:g **should** trigger an apparatus entry.

**Comment by wsalesky** [comment]
@paregorios All occurrences of t:g? or just t:g[@type='apostrophe']

**Comment by wsalesky** [comment]
@paregorios 
The updated branch builds an apparatus entry for `t:g[@type='apostrophe']`

**Comment by jcowey** [comment]
pretty sure that at this stage `t:g` should ONLY trigger apparatus when it is `t:g[@type='apostrophe']`
There are lots of `g types` that we do NOT want in the apparatus

**Comment by wsalesky** [comment]
Great. That matches current behavior.

**Comment by paregorios** [comment]
Yes, sorry, both @wsalesky and @jcowey are correct! ONLY trigger on g type apostrophe.

**Comment by paregorios** [comment]
I will test.
